env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
settings:
  react:
    version: detect
  'import/resolver':
    typescript:
      project: './'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - jest
  - import
rules:
  import/order:
    - 2
    - pathGroups:
        - pattern: '*'
          group: 'parent'
      groups:
        - [builtin, external]
        - parent
        - [sibling, index]
      newlines-between: 'always'
  '@typescript-eslint/no-explicit-any': 0
  no-console: ['warn']
globals:
  JSX: readonly
