name: Code Quality & Tests
on:
  - pull_request

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache multiple paths
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node version
        run: node --version
      - name: NPM version
        run: npm --version
      - name: Install Dependencies
        run: npm ci
      - name: Linter Check
        run: npm run lint
      - name: Prettier Check
        run: npm run prettier:check
      - name: TypeScript Check
        run: npm run ts:check
  unit-tests:
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache multiple paths
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Run tests and report coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npm run test:coverage
          annotations: none
