name: Publish

on:
  push:
    branches: [main]

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2.1.0
        
  # todo build

  publish-npm:
    name: Publish to NPM registry
    runs-on: ubuntu-latest
    needs:
      - check-version
    if: needs.check-version.outputs.changed == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # run npm ci to install husky for prepare script (before publish)
      # TODO: should be removed after fixing https://github.com/npm/cli/issues/3707
      - name: Install dependencies
        run: npm ci
      - name: Publish the package to NPM
        run: |
          echo "Publishing new version..."
          npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
